version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.19
    container_name: graylog_elasticsearch
    environment:
      - cluster.name=graylog
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - graylog-net
    restart: unless-stopped

  mongo:
    image: mongo:4.4
    container_name: graylog_mongo
    volumes:
      - mongodata:/data/db
    networks:
      - graylog-net
    restart: unless-stopped

  graylog:
    image: graylog/graylog:3.3.13
    container_name: graylog_server
    environment:
      GRAYLOG_CONTENT_PACKS_ENABLED: "true"
      GRAYLOG_CONTENT_PACKS_GROK_DISABLE: "false"
      GRAYLOG_ROOT_PASSWORD_SHA2: "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3"
      #GRAYLOG_ROOT_PASSWORD_HASH: "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3"
      GRAYLOG_WEB_ENDPOINT_URI: "http://10.10.10.71:9000/api"
      #GRAYLOG_HTTP_BIND_ADDRESS: "127.0.0.1:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://10.10.10.71:9000/"
      GRAYLOG_ROOT_TIMEZONE: "UTC"
      GRAYLOG_ENABLE_SSL: "false"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      GRAYLOG_MONGO_INITDB_DATABASE: "graylog"
      GRAYLOG_MONGO_URI: "mongodb://mongo:27017/graylog"
    volumes:
      - graylogdata:/usr/share/graylog/data
    ports:
      - "9000:9000"
      - "12201:12201"
      - "514:514"
      - "514:514/udp"
      - "6000:6000"
      - "6000:6000/udp"
    depends_on:
      - elasticsearch
      - mongo
    networks:
      - graylog-net
    restart: unless-stopped

volumes:
  esdata1:
  mongodata:
  graylogdata:

networks:
  graylog-net:
   driver: bridge 
