---  
- name: Создание структуры каталогов
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  loop:
    - { path: /app/config,       mode: '0755' }
    - { path: /app/graylog,      mode: '0777' }
    - { path: /app/elastic,      mode: '0777' }
    - { path: /app/elastic/log,  mode: '0755' }
    - { path: /app/mongodb,      mode: '0755' }
    - { path: /app/mongodb/log,  mode: '0755' }

- name: Развертывание файла конфига graylog
  template:
    src: templates/server.conf.j2
    dest: /app/config/server.conf
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname in groups['graylog_node']


- name: Формируем JSON для инициализации Replica Set
  delegate_to: localhost
  run_once: true
  template:
    src: rs_config.js.j2
    dest: /tmp/rs_config.js

- name: Показываем содержимое сгенерированного файла
  delegate_to: localhost
  run_once: true
  command: cat /tmp/rs_config.js
  register: rs_file

- name: Выводим его
  delegate_to: localhost
  run_once: true
  debug:
    var: rs_file.stdout_lines


#- name: Инициализируем Replica Set
#  community.mongodb.mongodb_shell:
#    login_host: localhost
#    login_port: 27017
#    eval: "rs.initiate({{ rs_config | to_json }})"