---
- name: Persist vm.max_map_count in /etc/sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^vm\.max_map_count'
    line: 'vm.max_map_count=262144'
    state: present

- name: Reload sysctl to apply changes from /etc/sysctl.conf
  command: sysctl -p
  changed_when: false